import { EngineerInput, ProjectInput } from '../scoring/types';

export interface SeedProject extends ProjectInput {
  name: string;
  durationMonths: number;
  commercialTier: number;
  sourceEmailBody: string;
}

export interface SeedEngineer extends EngineerInput {
  name: string;
  sourceSkillSheetBody: string;
}

export const seedProjects: SeedProject[] = [
  {
    name: 'ECサイトリニューアル案件',
    requiredSkills: [
      { name: 'React', minYears: 2, required: true },
      { name: 'TypeScript', minYears: 2, required: true },
      { name: 'AWS', minYears: 1, required: false },
    ],
    rateMin: 60,
    rateMax: 80,
    location: '東京都',
    remoteAllowed: true,
    startDate: '2026-10-01',
    durationMonths: 6,
    commercialTier: 1,
    japaneseLevel: 'business',
    sourceEmailBody:
      '【案件情報】ECサイトリニューアルのフロントエンドエンジニアを募集しています。React.js/TypeScript経験2年以上必須。AWS経験があれば尚可。稼働開始10月1日〜、フルリモート可、単価60〜80万円。',
  },
  {
    name: '基幹システム刷新プロジェクト',
    requiredSkills: [
      { name: 'Java', minYears: 5, required: true },
      { name: 'Spring Boot', minYears: 3, required: true },
      { name: 'Oracle', minYears: 2, required: false },
    ],
    rateMin: 65,
    rateMax: 85,
    location: '大阪府',
    remoteAllowed: false,
    startDate: '2026-09-15',
    durationMonths: 12,
    commercialTier: 2,
    japaneseLevel: 'business',
    sourceEmailBody:
      '基幹システム刷新プロジェクトのSE募集。Java(Spring)実務経験5年以上、Oracle経験者優遇。大阪勤務必須(常駐)。単価65〜85万。',
  },
  {
    name: '社内業務システム開発',
    requiredSkills: [
      { name: 'PHP', minYears: 2, required: true },
      { name: 'Laravel', minYears: 1, required: true },
    ],
    rateMin: 50,
    rateMax: 65,
    location: '東京都',
    remoteAllowed: true,
    startDate: '2026-10-15',
    durationMonths: 4,
    commercialTier: 1,
    japaneseLevel: 'none',
    sourceEmailBody: '社内業務システムのWeb開発。PHP/Laravel経験者募集。リモート勤務可。単価50〜65万円。',
  },
  {
    name: 'モバイルアプリ新規開発(Flutter)',
    requiredSkills: [{ name: 'Flutter', minYears: 1, required: true }],
    rateMin: 55,
    rateMax: 75,
    location: 'リモート',
    remoteAllowed: true,
    startDate: '2026-11-01',
    durationMonths: 3,
    commercialTier: 1,
    japaneseLevel: 'none',
    sourceEmailBody: 'Flutterによるモバイルアプリ新規開発。フルリモート案件。単価55〜75万。',
  },
  {
    name: 'クラウドインフラ構築・運用',
    requiredSkills: [
      { name: 'AWS', minYears: 3, required: true },
      { name: 'Docker', minYears: 2, required: true },
      { name: 'Kubernetes', minYears: 1, required: false },
    ],
    rateMin: 70,
    rateMax: 90,
    location: '神奈川県',
    remoteAllowed: false,
    startDate: '2026-09-01',
    durationMonths: 12,
    commercialTier: 1,
    japaneseLevel: 'business',
    sourceEmailBody: 'AWSクラウド基盤の構築・運用。Docker/K8s経験尚可。神奈川県内常駐必須。単価70〜90万。',
  },
  {
    name: 'データ分析基盤構築',
    requiredSkills: [
      { name: 'Python', minYears: 3, required: true },
      { name: 'GCP', minYears: 1, required: false },
    ],
    rateMin: 60,
    rateMax: 90,
    location: 'リモート',
    remoteAllowed: true,
    startDate: '2026-10-01',
    durationMonths: 6,
    commercialTier: 1,
    japaneseLevel: 'business',
    sourceEmailBody: 'データ分析基盤の設計・構築。Python実務経験3年以上。GCP経験者優遇。フルリモート。単価60〜90万。',
  },
  {
    name: '金融系システム保守',
    requiredSkills: [
      { name: 'Java', minYears: 3, required: true },
      { name: 'Oracle', minYears: 3, required: true },
    ],
    rateMin: 55,
    rateMax: 70,
    location: '東京都',
    remoteAllowed: false,
    startDate: '2026-09-01',
    durationMonths: 12,
    commercialTier: 3,
    japaneseLevel: 'native',
    sourceEmailBody:
      '金融系基幹システムの保守案件。Java/Oracle経験必須。3次請けのため日本語ネイティブレベル必須。東京常駐。単価55〜70万。',
  },
  {
    name: 'ネットワーク構築PMO支援',
    requiredSkills: [
      { name: 'PMO', minYears: 2, required: true },
      { name: 'ネットワーク', minYears: 3, required: true },
    ],
    rateMin: 80,
    rateMax: 100,
    location: '東京都',
    remoteAllowed: true,
    startDate: '2026-11-15',
    durationMonths: 6,
    commercialTier: 1,
    japaneseLevel: 'business',
    sourceEmailBody: '大規模ネットワーク構築プロジェクトのPMO支援。ネットワーク実務経験3年以上。一部リモート可。単価80〜100万。',
  },
  {
    name: 'ECバックエンドAPI開発',
    requiredSkills: [
      { name: 'Node.js', minYears: 2, required: true },
      { name: 'TypeScript', minYears: 1, required: false },
    ],
    rateMin: 55,
    rateMax: 75,
    location: '福岡県',
    remoteAllowed: true,
    startDate: '2026-10-01',
    durationMonths: 6,
    commercialTier: 1,
    japaneseLevel: 'business',
    sourceEmailBody: 'ECサイトのバックエンドAPI開発。Node.js実務経験2年以上。TypeScript尚可。リモート可。単価55〜75万。',
  },
  {
    name: '大規模ECサイト基盤刷新',
    requiredSkills: [
      { name: 'React', minYears: 3, required: true },
      { name: 'AWS', minYears: 2, required: true },
      { name: 'Docker', minYears: 1, required: false },
    ],
    rateMin: 65,
    rateMax: 90,
    location: '東京都',
    remoteAllowed: true,
    startDate: '2026-09-15',
    durationMonths: 9,
    commercialTier: 1,
    japaneseLevel: 'business',
    sourceEmailBody: '大規模ECサイトの基盤刷新プロジェクト。React/AWS実務経験必須。Docker尚可。リモート可。単価65〜90万。',
  },
];

export const seedEngineers: SeedEngineer[] = [
  {
    name: '山田太郎',
    skills: [
      { name: 'ReactJS', years: 4 },
      { name: 'TypeScript', years: 3 },
      { name: 'AWS', years: 2 },
    ],
    desiredRateMin: 65,
    desiredRateMax: 80,
    desiredLocations: ['東京都', '神奈川県'],
    remoteDesired: true,
    availableFrom: '2026-10-01',
    japaneseLevel: 'business',
    sourceSkillSheetBody: '【スキルシート】山田太郎。React.js/TypeScript実務4年。AWS構築経験あり。希望単価65〜80万。',
  },
  {
    name: '佐藤花子',
    skills: [
      { name: 'Java', years: 6 },
      { name: 'SpringBoot', years: 4 },
      { name: 'Oracle Database', years: 3 },
    ],
    desiredRateMin: 65,
    desiredRateMax: 85,
    desiredLocations: ['大阪府', '京都府'],
    remoteDesired: false,
    availableFrom: '2026-09-15',
    japaneseLevel: 'native',
    sourceSkillSheetBody: '佐藤花子。Java/Spring Boot実務6年、Oracle3年。大阪近郊の常駐案件希望。',
  },
  {
    name: '鈴木一郎',
    skills: [
      { name: 'PHP', years: 3 },
      { name: 'Laravel', years: 2 },
    ],
    desiredRateMin: 50,
    desiredRateMax: 60,
    desiredLocations: ['東京都'],
    remoteDesired: true,
    availableFrom: '2026-10-01',
    japaneseLevel: 'business',
    sourceSkillSheetBody: '鈴木一郎。PHP/Laravel実務3年。フルリモート希望。単価50〜60万。',
  },
  {
    name: '田中健',
    skills: [{ name: 'Flutter', years: 2 }],
    desiredRateMin: 55,
    desiredRateMax: 70,
    desiredLocations: ['大阪府'],
    remoteDesired: true,
    availableFrom: '2026-11-01',
    japaneseLevel: 'business',
    sourceSkillSheetBody: '田中健。Flutter実務2年。リモート案件希望。単価55〜70万。',
  },
  {
    name: '高橋美咲',
    skills: [
      { name: 'Amazon Web Services', years: 4 },
      { name: 'Docker', years: 3 },
      { name: 'K8s', years: 1 },
    ],
    desiredRateMin: 70,
    desiredRateMax: 90,
    desiredLocations: ['神奈川県', '東京都'],
    remoteDesired: false,
    availableFrom: '2026-09-01',
    japaneseLevel: 'business',
    sourceSkillSheetBody: '高橋美咲。AWS4年、Docker3年、Kubernetes1年。神奈川近郊常駐希望。単価70〜90万。',
  },
  {
    name: '伊藤修',
    skills: [
      { name: 'Python', years: 5 },
      { name: 'Google Cloud Platform', years: 2 },
    ],
    desiredRateMin: 60,
    desiredRateMax: 85,
    desiredLocations: ['東京都'],
    remoteDesired: true,
    availableFrom: '2026-10-01',
    japaneseLevel: 'business',
    sourceSkillSheetBody: '伊藤修。Python実務5年、GCP2年。フルリモート希望。単価60〜85万。',
  },
  {
    name: '渡辺蓮',
    skills: [
      { name: 'Java', years: 2 },
      { name: 'MySQL', years: 2 },
    ],
    desiredRateMin: 50,
    desiredRateMax: 65,
    desiredLocations: ['東京都'],
    remoteDesired: false,
    availableFrom: '2026-09-01',
    japaneseLevel: 'N2',
    sourceSkillSheetBody: '渡辺蓮。Java実務2年、MySQL2年。日本語レベルN2。東京勤務希望。',
  },
  {
    name: '中村誠',
    skills: [
      { name: 'PMO', years: 3 },
      { name: 'Network', years: 4 },
    ],
    desiredRateMin: 80,
    desiredRateMax: 95,
    desiredLocations: ['東京都'],
    remoteDesired: true,
    availableFrom: '2026-11-15',
    japaneseLevel: 'business',
    sourceSkillSheetBody: '中村誠。PMO実務3年、ネットワーク実務4年。単価80〜95万。一部リモート可。',
  },
  {
    name: '小林陽子',
    skills: [
      { name: 'Node', years: 3 },
      { name: 'TypeScript', years: 2 },
    ],
    desiredRateMin: 55,
    desiredRateMax: 75,
    desiredLocations: ['福岡県', 'リモート'],
    remoteDesired: true,
    availableFrom: '2026-10-01',
    japaneseLevel: 'business',
    sourceSkillSheetBody: '小林陽子。Node.js実務3年、TypeScript2年。フルリモート希望。単価55〜75万。',
  },
  {
    name: '加藤大輔',
    skills: [
      { name: 'React.js', years: 3 },
      { name: 'AWS', years: 3 },
      { name: 'Docker', years: 1 },
    ],
    desiredRateMin: 60,
    desiredRateMax: 85,
    desiredLocations: ['東京都'],
    remoteDesired: true,
    availableFrom: '2026-09-20',
    japaneseLevel: 'business',
    sourceSkillSheetBody: '加藤大輔。React実務3年、AWS3年、Docker1年。単価60〜85万。リモート希望。',
  },
];
