import { Company, Talent } from '../src/types';

export interface SeedTalent extends Omit<Talent, 'id' | 'uid'> {
  email: string;
}
export interface SeedCompany extends Omit<Company, 'id' | 'uid'> {
  email: string;
}

export const SEED_TALENTS: SeedTalent[] = [
  {
    email: 'talent1@example.com',
    name: '田中 健一',
    skills: ['経理', 'EC運営', 'Webマーケ'],
    interestedIndustries: ['製造業', '卸売業'],
    weeklyAvailableHours: 10,
    workStyle: 'both',
    relocatable: true,
    prefecture: '長野県',
    successionInterestLevel: 5,
    fundingCapacity: 1200,
    bio: '大手製造業で経理・EC運営を10年経験。将来は地方の製造業の事業承継に携わりたい。',
  },
  {
    email: 'talent2@example.com',
    name: '佐藤 美咲',
    skills: ['Webデザイン', 'SNS運用', 'EC運営'],
    interestedIndustries: ['飲食業', '観光業'],
    weeklyAvailableHours: 5,
    workStyle: 'remote',
    relocatable: false,
    prefecture: '東京都',
    successionInterestLevel: 2,
    fundingCapacity: 100,
    bio: 'フリーランスのWebデザイナー。副業の範囲でスポット的に関わりたい。',
  },
  {
    email: 'talent3@example.com',
    name: '鈴木 大輔',
    skills: ['製造業経験', '生産管理', '品質管理'],
    interestedIndustries: ['製造業'],
    weeklyAvailableHours: 15,
    workStyle: 'onsite',
    relocatable: true,
    prefecture: '愛知県',
    successionInterestLevel: 4,
    fundingCapacity: 800,
    bio: '精密機械メーカーで生産管理を15年。現場に入って改善から関わりたい。',
  },
  {
    email: 'talent4@example.com',
    name: '山本 花子',
    skills: ['経営企画', '財務', 'M&A'],
    interestedIndustries: ['小売業', '卸売業'],
    weeklyAvailableHours: 8,
    workStyle: 'both',
    relocatable: true,
    prefecture: '大阪府',
    successionInterestLevel: 5,
    fundingCapacity: 2000,
    bio: '事業会社で経営企画・M&A実務に従事。将来的な独立・事業承継を検討中。',
  },
  {
    email: 'talent5@example.com',
    name: '高橋 拓也',
    skills: ['農業経験', 'EC運営', '観光開発'],
    interestedIndustries: ['農業', '観光業'],
    weeklyAvailableHours: 20,
    workStyle: 'onsite',
    relocatable: false,
    prefecture: '北海道',
    successionInterestLevel: 3,
    fundingCapacity: 300,
    bio: '地元北海道で農業関連のEC支援をしている。地元から離れずに関われる先を探したい。',
  },
];

export const SEED_COMPANIES: SeedCompany[] = [
  {
    email: 'company1@example.com',
    name: '有限会社信州フーズ',
    industry: '製造業',
    prefecture: '長野県',
    overview: '長野県の味噌・漬物製造業。地元産の原料にこだわった加工食品を製造。後継者不在が課題。',
    financialHealth: 'average',
    wantedPersonaTags: ['経理', 'EC運営', 'Webマーケ'],
    wantedPersonaTagWeights: { 経理: 2, EC運営: 1.5, Webマーケ: 1 },
    sideJobAcceptable: true,
    requiredWeeklyHours: { min: 5, max: 15 },
    successionTimeframe: '1-3y',
  },
  {
    email: 'company2@example.com',
    name: '株式会社湘南デザイン工房',
    industry: '飲食業',
    prefecture: '神奈川県',
    overview: '湘南エリアでカフェを3店舗運営。ブランディングとSNS発信を強化したい。',
    financialHealth: 'good',
    wantedPersonaTags: ['Webデザイン', 'SNS運用'],
    sideJobAcceptable: true,
    requiredWeeklyHours: { min: 3, max: 8 },
    successionTimeframe: '5y+',
  },
  {
    email: 'company3@example.com',
    name: '中京精密工業株式会社',
    industry: '製造業',
    prefecture: '愛知県',
    overview: '自動車部品向け精密加工業。創業者が高齢で早期の後継者確保が急務。',
    financialHealth: 'needs_improvement',
    wantedPersonaTags: ['生産管理', '品質管理', '製造業経験'],
    wantedPersonaTagWeights: { 製造業経験: 2 },
    sideJobAcceptable: true,
    requiredWeeklyHours: { min: 10, max: 20 },
    successionTimeframe: 'immediate',
  },
  {
    email: 'company4@example.com',
    name: '浪速商事株式会社',
    industry: '卸売業',
    prefecture: '大阪府',
    overview: '関西圏の食品卸売業。経営企画・財務に強い後継候補を求めている。',
    financialHealth: 'good',
    wantedPersonaTags: ['経営企画', '財務', 'M&A'],
    sideJobAcceptable: true,
    requiredWeeklyHours: { min: 5, max: 10 },
    successionTimeframe: '1-3y',
  },
  {
    email: 'company5@example.com',
    name: '有限会社十勝ファーム',
    industry: '農業',
    prefecture: '北海道',
    overview: '十勝地方の畑作農家。まずは正社員候補を求めており副業からの受け入れは現状不可。',
    financialHealth: 'average',
    wantedPersonaTags: ['農業経験', 'EC運営'],
    sideJobAcceptable: false,
    requiredWeeklyHours: { min: 30, max: 40 },
    successionTimeframe: '3-5y',
  },
];

export const SEED_PASSWORD = 'password123!';
